# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URCPP = $(shell $(shell urweb -print-ccompiler) -print-prog-name=g++)
URINCL = -I$(shell urweb -print-cinclude) 
URVERSION = $(shell urweb -version)
.PHONY: all
all: ./Makefile ./test/UTF8_test1.exe ./test/UTF8_test1.sql
./test/UTF8_test1.exe: .fix-multy1
./test/UTF8_test1.urp: ./Makefile ./lib.urp ./test/UTF8_test1.ur .cake3/tmp__testUTF8_test1_in
	cat .cake3/tmp__testUTF8_test1_in > ./test/UTF8_test1.urp
.cake3/tmp__testUTF8_test1_in: ./Makefile
	-rm -rf .cake3/tmp__testUTF8_test1_in
	echo 'database dbname=UTF8_test1' >> .cake3/tmp__testUTF8_test1_in
	echo 'sql .././test/UTF8_test1.sql' >> .cake3/tmp__testUTF8_test1_in
	echo 'library ../.' >> .cake3/tmp__testUTF8_test1_in
	echo '' >> .cake3/tmp__testUTF8_test1_in
	echo '$$/list' >> .cake3/tmp__testUTF8_test1_in
	echo '$$/char' >> .cake3/tmp__testUTF8_test1_in
	echo '$$/string' >> .cake3/tmp__testUTF8_test1_in
	echo '.././test/UTF8_test1' >> .cake3/tmp__testUTF8_test1_in
./lib.urp: ./Makefile ./UTF8.ur ./UTF8_ffi.h ./UTF8_ffi.o .cake3/tmp__lib_in
	cat .cake3/tmp__lib_in > ./lib.urp
.cake3/tmp__lib_in: ./Makefile
	-rm -rf .cake3/tmp__lib_in
	echo 'ffi ./UTF8_ffi' >> .cake3/tmp__lib_in
	echo 'include ./UTF8_ffi.h' >> .cake3/tmp__lib_in
	echo 'link ./UTF8_ffi.o' >> .cake3/tmp__lib_in
	echo 'link -lstdc++ -lutf8proc' >> .cake3/tmp__lib_in
	echo '' >> .cake3/tmp__lib_in
	echo '$$/list' >> .cake3/tmp__lib_in
	echo './UTF8' >> .cake3/tmp__lib_in
.PHONY: lib
lib: ./Makefile ./lib.urp
./UTF8_ffi.o: ./Makefile ./UTF8_ffi.cpp $(call GUARD,URCPP) $(call GUARD,URINCL) $(call GUARD,UR_CFLAGS)
	$(URCPP) -c $(UR_CFLAGS) $(URINCL) -std=c++11 -o ./UTF8_ffi.o ./UTF8_ffi.cpp
./test/UTF8_test1.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: ./Makefile ./test/UTF8_test1.urp $(call GUARD,URVERSION)
	urweb -dbms sqlite ./test/UTF8_test1
$(call GUARD,URCPP):
	rm -f .cake3/GUARD_URCPP_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@
$(call GUARD,URVERSION):
	rm -f .cake3/GUARD_URVERSION_*
	touch $@
$(call GUARD,UR_CFLAGS):
	rm -f .cake3/GUARD_UR_CFLAGS_*
	touch $@

else

# Prebuild/postbuild section

ifneq ($(MAKECMDGOALS),clean)

.PHONY: all
all: .fix-multy1
.PHONY: ./test/UTF8_test1.exe
./test/UTF8_test1.exe: .fix-multy1
.PHONY: ./test/UTF8_test1.urp
./test/UTF8_test1.urp: .fix-multy1
.PHONY: .cake3/tmp__testUTF8_test1_in
.cake3/tmp__testUTF8_test1_in: .fix-multy1
.PHONY: ./lib.urp
./lib.urp: .fix-multy1
.PHONY: .cake3/tmp__lib_in
.cake3/tmp__lib_in: .fix-multy1
.PHONY: lib
lib: .fix-multy1
.PHONY: ./UTF8_ffi.o
./UTF8_ffi.o: .fix-multy1
.PHONY: ./test/UTF8_test1.sql
./test/UTF8_test1.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	MAIN=1 $(MAKE) -f ./Makefile $(MAKECMDGOALS)

endif
.PHONY: clean
clean: 
	-rm ./UTF8_ffi.o ./lib.urp ./test/UTF8_test1.exe ./test/UTF8_test1.sql ./test/UTF8_test1.urp .cake3/tmp__lib_in .cake3/tmp__testUTF8_test1_in
	-rm -rf .cake3

endif
